mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('slide.urls')),
    url(r'^admin/', admin.site.urls),
]

slide/urls.py
from django.conf.urls import url

from . import views

app_name = 'slide'
urlpatterns = [
##### FOR VIEWING #####
    url(r'^$', views.index, name='index'),
    url(r'^draft$', views.quickDraft, name='quickDraft'),
    url(r'^new$', views.newSlide, name='newSlide'),
    url(r'^edit$', views.edit, name='edit'),
    url(r'^show$', views.showList, name='showList'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^download$', views.download, name='download'),
##### NOT FOR VIEWING #####
    url(r'^store$', views.store, name='store'),
    url(r'^delete$', views.delete, name='delete'),
    url(r'^save$', views.save, name='save'),
    url(r'^uploaded$', views.uploaded, name='uploaded'),
    url(r'^converted$', views.converted, name='converted'),
]

slide/models.py
from django.db import models

# Create your models here.

class R_Text(models.Model):
    name_text = models.CharField(max_length=200)
    data_text = models.CharField(max_length=9999999)
    style_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.name_text

slide/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.core.files.storage import default_storage
from .models import R_Text
from django.utils import timezone
import os
import json as simplejson
def index(request):
    return render(request,'index.html',None)

def download(request):
    textfile = open('slide/static/download.rst','w')
    existSlide = R_Text.objects.filter(name_text=request.GET['name'])
    print(existSlide)
    for item in existSlide:
        print('item found')
        textfile.write(item.data_text)
        slide_type = item.style_text
    textfile.close()
    foldername = ''
    for char in request.GET['name']:
        if char == ' ':
            foldername = foldername+'''_'''
        else:
            foldername = foldername+char
    if slide_type == 'CLEAN':
        os.system('rst2html5 slide/static/download.rst > slide/static/'+foldername+'/download.html')
    elif slide_type == 'DECK':
        os.system('rst2html5 --deck-js --pretty-print-code --embed-content slide/static/download.rst > slide/static/'+foldername+'/download.html')
    elif slide_type == 'REVAL':
        os.system('rst2html5 --jquery --reveal-js --pretty-print-code slide/static/download.rst > slide/static/'+foldername+'/download.html')
    elif slide_type == 'BOOTSTRAP':
        os.system('rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content slide/static/download.rst > slide/static/'+foldername+'/download.html')
    context  = {'name' : request.GET['name'], 'path' : '/static/'+foldername+'/download.html'}
    return render(request,'download.html',context)

def quickDraft(request):
    return render(request,'quick.html',None)

def converted(request):
    textfile = open('slide/static/rst.rst','w')
    if('name' not in request.GET):
        textfile.write(request.GET['text'])    
        slide_type = request.GET['type']
    elif('name' in request.GET):
        existSlide = R_Text.objects.filter(name_text=request.GET['name'])
        print(existSlide)
        for item in existSlide:
            print('item found')
            textfile.write(item.data_text)
            slide_type = item.style_text
        
    textfile.close()  
    if slide_type == 'CLEAN':
        os.system('rst2html5 slide/static/rst.rst > slide/templates/display.html')
    elif slide_type == 'DECK':
        os.system('rst2html5 --deck-js --pretty-print-code --embed-content slide/static/rst.rst > slide/templates/display.html')
    elif slide_type == 'REVAL':
        os.system('rst2html5 --jquery --reveal-js --pretty-print-code slide/static/rst.rst > slide/templates/display.html')
    elif slide_type == 'BOOTSTRAP':
        os.system('rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content slide/static/rst.rst > slide/templates/display.html')
    list_text = []
    htmlfile = open('slide/templates/display.html','r')
    for text in htmlfile:
        list_text.append(text)
    htmlfile.close()
    htmlfile = open('slide/static/display.html','w')
    for text in list_text:
        htmlfile.write(text)
    htmlfile.close()
    #htmlfile.write("{% load staticfiles %}")
    os.system('rm slide/static/rst.rst')
    slide = R_Text.objects.filter(name_text__icontains='')
    #for item in slide:
    #    print(item.data_text)
    return render(request,'display.html',None)

def newSlide(request):
    slide = R_Text.objects.filter(name_text__icontains='')
    names = []
    for item in slide:
        names.append(item.name_text)
    json_list = simplejson.dumps(names)
    return render(request,'new.html',{'json_list': json_list})


def store(request):
    if(request.POST):
        new_slide = R_Text(name_text=request.POST['name'],data_text=request.POST['text'],style_text=request.POST['type'],pub_date=timezone.now())
        new_slide.save()
    slide = R_Text.objects.filter(name_text__icontains='')
    for item in slide:
        print(item)
    new_name = ''
    for char in request.POST['name']:
        if char == ' ':
            new_name = new_name+'''_'''
        else:
            new_name = new_name+char
    print(new_name)
    os.system('mkdir slide/static/'+new_name)
    return redirect('/show')

def showList(request):
    all_slide = R_Text.objects.filter(name_text__icontains='').order_by('name_text')
    names = []
    for name in all_slide:
        #print(name.name_text)
        names.append(name.name_text)
    #context = { 'slide' : all_slide}
    #context = { 'slide' : ['s','s']}
    json_list = simplejson.dumps(names)
    return render(request,'show.html',{'json_list': json_list})


def delete(request):
    slide = R_Text.objects.filter(name_text=request.GET['name'])
    slide.delete()
    new_name = ''
    for char in request.GET['name']:
        if char == ' ':
            new_name = new_name+'''_'''
        else:
            new_name = new_name+char
    os.system('rm -r slide/static/'+new_name)
    return redirect('/show')

def edit(request):
    slide = R_Text.objects.filter(name_text=request.GET['name'])
    print('haha')
    return render(request,'edit.html',{'slide': slide})

def save(request):
    slide = R_Text.objects.filter(name_text=request.POST['name'])
    for item in slide:
        item.data_text = request.POST['text']
        #print(request.POST['type'])
        item.style_text = request.POST['type']
        item.save()
    return redirect('/show')

def upload(request):
    all_slide = R_Text.objects.filter(name_text__icontains='').order_by('name_text')
    names = []
    for name in all_slide:
        names.append(name.name_text)
    return render(request,'upload.html',{'names': names})   


def uploaded(request):
    new_name = ''
    for char in request.POST['name']:
        if char == ' ':
            new_name = new_name+'''_'''
        else:
            new_name = new_name+char
    path = 'slide/static/'+new_name+'/'
    img_file = request.FILES['input_file']
    file_path = default_storage.save(path, img_file)
    print(request.POST['file_name']+'sdfsadfsdf')
    new_name = ''
    for char in request.POST['file_name']:
        if char == ' ':
            new_name = new_name+'''_'''
        else:
            new_name = new_name+char    
    os.rename(file_path, path+new_name)
    return redirect('/upload')

slide/templates/display.html
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><style type="text/css">body{
 font-family: helvetica;
 color: #222;
}

li>p{
 margin-bottom: 0;
}

.line{
 margin-bottom: 0.3em;
 display: table;
}

.admonition-title {
    font-size: 1.3em;
    font-weight: bold;
}

aside{
 float: right;
 width: 20%;
 display: table;
 padding: 1em;
 margin: 1em;
 margin-right: 0;
}

.footnote, .cite{
 width: 98%;
 display: table;
 border: 1px solid #ddd;
 padding: 0.5%;
 margin: 0.5%;
}

.footnote .du-label, .cite .du-label{
 float: left;
 height: 100%;
 width: 5%;
 margin-right: 1em;
 padding: 0.5%;
 text-align: center;
 display: table;
}

th, th p{
 font-weight: bold;
}

.field-label{
 font-weight: bold;
}

ol.arabic{
 list-style-type: decimal;
}

ol.loweralpha{
 list-style-type: lower-alpha;
}

ol.upperalpha{
 list-style-type: upper-alpha;
}

ol.lowerroman{
 list-style-type: lower-roman;
}

ol.upperroman{
 list-style-type: upper-roman;
}

img.align-left{
 float: left;
}

img.align-right{
 float: right;
}
</style></head><body><section id="rst2html5"><header><h2>rst2html5</h2></header><ul><li><p>what is it?</p></li><li><p>who created it?</p></li><li><p>what does it do?</p></li><li><p>status</p></li><li><p>future</p></li><li><p>contribute</p></li></ul></section><section id="what-is-it"><header><h2>what is it?</h2></header><ul><li><p>a program that transforms restructured text</p></li><li><p>into html5 markup with css3 styles</p></li><li><p>that allows to post process it</p></li></ul></section><section id="who-created-it"><header><h2>who created it?</h2></header><ul><li><p>Mariano Guerra</p></li></ul><section id="hi"><header><h3>hi!</h3></header><img alt="static/Simple_RST_Slide/spongebob.jpg" src="static/Simple_RST_Slide/spongebob.jpg"></section></section><section id="what-does-it-do"><header><h2>what does it do?</h2></header><ul><li><p>stuff like this presentation</p></li></ul><section id="some-code"><header><h3>some code</h3></header><pre class="prettyprint lang-python">import antigravity
the_anwser = 42</pre><pre class="prettyprint lang-html">&lt;html&gt;
 &lt;head&gt;
  &lt;title&gt;hi&lt;/title&gt;
 &lt;/head&gt;

 &lt;body&gt;
  &lt;h1&gt;hi!&lt;/h1&gt;
 &lt;/body&gt;
&lt;/html&gt;</pre></section><section id="some-quote"><header><h3>some quote</h3></header><blockquote><p>Before I speak, I have something important to say.</p></blockquote></section></section><section id="status"><header><h2>status</h2></header><ul><li><p>works <a class="footnote-reference" href="#id2" id="id1">*</a></p></li></ul><div id="id2"><div class="du-label">*</div><p>needs some battle testing</p></div></section><section id="future"><header><h2>future</h2></header><ul><li><p>add more transformations</p></li><li><p>add more plugin options</p></li><li><p>add an authoring tool for it</p></li><li><p>promote</p></li><li><p>document</p></li></ul></section><section id="contribute"><header><h2>contribute</h2></header><ul><li></li></ul></section></body></html>

slide/templates/download.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<html>
<title>RST2HTML5</title>
<center><b><h1>{{ name }}</h1></b>
<a class=button download="{{ name }}.html" href={{ path }}>Download Link</a>  
</center>	
</html>

slide/templates/edit.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<html>

<title>RST2HTML5</title>
<center>
<b><h1>Edit Slide</h1></b>
<form name="myForm" action="{% url 'slide:save'%}" onsubmit="return validateForm()" method="post">
{% csrf_token %}
{% for item in slide %}
Name : {{ item.name_text }}<input id='name' type='hidden' name="name" value="{{ item.name_text }}">
<br><br>
Text Size : <input type="number" id='size' value='30' name="size" min="12" max="30" onClick='setSize()' onchange="setSize()">
<br>
<br>
<textarea rows="50" cols="80" id='text' name='text'>{{ item.data_text }}</textarea>
<br>
<div class='select-style''>
Style : <select id="select" name='type'>
<option>CLEAN</option>
<option>DECK</option>
<option>REVAL</option>
<option>BOOTSTRAP</option>
</select><hr><input class=button type='submit' value='Save'></div>
</form>
</center>
{% endfor %}


<p id="demo"></p>
<script>
function validateForm(){
    var check_name = document.forms["myForm"]["name"].value;
    var check_text = document.forms["myForm"]["text"].value;
    if (check_name == null || check_name == "") {
        alert("Name must be filled out");
        return false;
    }
    else if (check_text == null || check_text == "") {
        alert("Text must be filled out");
        return false;
    }
    else{
        return true;
    }
    
}
function setSize(){
    document.getElementById("text").style.fontSize = document.getElementById("size").value;
}
</script>	
</html>

slide/templates/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<html>
<title>RST2HTML5</title>
<center><b><h1>Service</h1></b>
<a class=button href="{% url 'slide:showList' %}">View Created Slide</a>
<br>
<br>
<a class=button href="{% url 'slide:newSlide' %}">Create New Slide</a>
<br>
<br>
<a class=button href="{% url 'slide:quickDraft' %}">Quick Draft</a>
<br>
<br>
<a class=button href="{% url 'slide:upload' %}">Upload Image</a>  
</center>
</html>

slide/templates/new.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'data/spongebob.jpg' %}" />
<html>

<title>RST2HTML5</title>
<center>
<b><h1>Create New Slide</h1></b>

<form id="myform" name="myForm" action="{% url 'slide:store' %}" onsubmit="return validateForm()" method="post">
{% csrf_token %}
Name : <input id='name' type='text' name="name" onchange="setLink()">
<br><br>
Text Size : <input type="number" id='size' value='30' name="size" min="12" max="30" onClick='setSize()' onchange="setSize()"><br><br>
Image Link : <input type="text" name="image" value=".. image:: static//<Image Name>" id="image" readonly>
<br>
<br>
<textarea rows="50" cols="80" id='text' name='text'></textarea>
<br>
<div class='select-style''>
Style : <select id="select" name='type'>
<option>CLEAN</option>
<option>DECK</option>
<option>REVAL</option>
<option>BOOTSTRAP</option>
</select><hr><input class=button type='submit' value='Create'>

</div>
</center>

</form>
<form action="{% url 'slide:converted' %}" onclick="return setURL()" method="get" target="_blank">
<input type="hidden" name='text' id='text2'>
<input type="hidden" name='type' id='select2'>
<center>
<input class=button type="submit" value="Preview">
</center>
</form>
<script>
function validateForm(){
    var check_name = document.forms["myForm"]["name"].value;
    var check_text = document.forms["myForm"]["text"].value;
    var check_dupl = {{ json_list|safe }}
    for(i = 0; i < check_dupl.length; i++){
        if(check_dupl[i] == check_name){
            alert("Name alread used")
            return false;
        }
    }
    if (check_name == null || check_name == "") {
        alert("Name must be filled out");
        return false;
    }
    else if (check_text == null || check_text == "") {
        alert("Text must be filled out");
        return false;
    }
    else{
        return true;
    }
    
}
function setSize(){
    document.getElementById("text").style.fontSize = document.getElementById("size").value;
}
function setLink(){
    var new_name = ""
    var name = trim(document.getElementById("name").value)
    for(i = 0; i < name.length; i++){
        if(name.charAt(i) == ' '){
        new_name = new_name + "_";
        }
        else{
        new_name = new_name + name.charAt(i);
        }
    }
    document.getElementById("image").value = ".. image:: static/"+new_name+"/<Image Name>";
}
function setURL(){
    document.getElementById("text2").value = document.getElementById("text").value;
    document.getElementById("select2").value = document.getElementById("select").value;
    return true;   
}
function trim(s){ 
  return ( s || '' ).replace( /^\s+|\s+$/g, '' ); 
}

</script>	
</html>

slide/templates/quick.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<html>
<title>RST2HTML5</title>
<center><b><h1>Convert from RST to HTML</h1></b>
<form action="{% url 'slide:converted' %}" method='get'>
<h3>Insert RST Below</h3><br>
<textarea rows="50" cols="175" name='text'></textarea>
<br>
<div class='select-style''>
<select id="select" name='type'>
<option>CLEAN</option>
<option>DECK</option>
<option>REVAL</option>
<option>BOOTSTRAP</option>
</select><hr><input class=button type='submit' value='Convert'></div>
</form> 
</center>	
</html>

slide/templates/show(old).html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<html>
<title>RST2HTML5</title>
<center><b><h1>Created Slide</h1></b>
{% for name in slide %}
<a class=button href="{% url 'slide:converted' %}?name={{ name.name_text }}&type={{ name.style_text }}"+"hello">{{ name }}({{ name.style_text }})</a>
<br><br>
{% endfor %}
</center>	
</html>

slide/templates/show.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<html>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
<body>
<center>
{% verbatim myblock %}

<div ng-app="myApp" ng-controller="namesCtrl">

<h1>Created Slide</h1>

<p><input type="text" ng-model="test" placeholder='Search Here'></p>

  <div ng-repeat="x in names | filter:test">
  <a class=button href="converted?name={{ x }}">
    {{ x }}<input type=hidden value={{ x }}>
  </a>    <a class=button_nw href="edit?name={{ x }}">EDIT</a>    <a class=button_nw href="download?name={{ x }}"><font color="blue">Download</font></a>    
<a class=button_nw onclick="return confirmDel();"  href="delete?name={{ x }}"><font color="red">X</font></a>        
  <br><br>
  </div>
  {{ name }}
</div>
{% endverbatim myblock %}
</center>
<script>
var x = 0;
angular.module('myApp', []).controller('namesCtrl', function($scope, $http) {
    $scope.names = {{ json_list|safe }};

});

function confirmDel(){
    var del = confirm("Confirm Delete?");
    return del
}

</script>

</body>
</html>

slide/templates/upload.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<html>
<title>RST2HTML5</title>


<center>
<h1>Upload Image</h1>

<form action="{% url 'slide:uploaded' %}" onsubmit="return checkFile();" method='post' enctype="multipart/form-data">
{% csrf_token %}
</div>            
<input type="file" name="input_file" id="input_file">
<input type="hidden" name="file_name" id="file_name">
<br><br>
<div class='select-style''>
Project : <select id="select" name='name'>
{% for item in names %}
<option>{{ item }}</option>
{% endfor %}
</select>
<br><br>
<input class='button' type="submit" value="Upload Image" name="submit">
</form>
<br><br>
<p><font color="red" id="msg"></font><p>
</center>

<script>
function checkFile (){
    var x = document.getElementById("input_file").value;
    var img_file = [".jpg",".png",".jpeg",".gif"];
    for(i = 0; i < img_file.length;i++){
        if( x.endsWith(img_file[i]) ){
            document.getElementById("file_name").value = x;
            return true;
        }
    }
    document.getElementById("msg").innerHTML = "NOT IMAGE FILE";

    return false;
}
String.prototype.endsWith = function(suffix) {
    return this.indexOf(suffix, this.length - suffix.length) !== -1;
};
</script>
</html>